### ISSUE TITLE
How can we/the Citrix community contribute code to this project?

### ISSUE THREAD

**Issue by j7lloyd** [citrix/terraform-provider-citrix#40]
I recently created a private fork of this repository to work on some prototype code that introduces support for additional/missing custom properties and capabilities within the `citrix_machine_catalog` resource. Specifically, I focused on the `azure_machine_config` context, to address the following:

- LicenseType
- UseSharedImageGallery
- SharedImageGalleryReplicaRatio
- SharedImageGalleryReplicaMaximum
- UseEphemeralOsDisk
- DiskEncryptionSetId

While the code isn't fully tested or documented at this stage, it sufficiently proves the concept. However, to ensure these enhancements are promptly released to benefit the community, I'm eager to move forward collaboratively, so may I propose the following steps:

1. Fork the repository publicly.
2. Implement the proposed code changes.
3. Submit a pull request for your review and feedback.

I look forward to your thoughts on the best way to proceed and appreciate your support in advancing this project.

**Comment by zhuolun-citrix** [comment]
Hi @j7lloyd ,

Thank you very much for your interest in contributing to our Citrix Terraform Provider repository. I see that you are trying to add support for some of the missing custom properties in machine catalog.

It would be very helpful if you can open a PR with your existing code for proof of concept so that we understand better on the issue or missing pieces, as well as your proposal on the updates / fixes to be made.

As for merging your PR, since our Terraform Provider is currently still in Tech-Preview, we may not be able to take your PR as is for the moment. As you can tell, our code evolves in a very fast pace and there are a lot of refactoring going on for optimizing user experience on the schema level, and improving code structure. So taking external PR will be challenging at this point. We are still working on the process to enable this workflow.

We still strongly encourage you to open a PR for showing the potential improvement / fix so that we can understand them better. We are very excited for your proposed solution, and are very interested to see your input in the future direction of our Terraform Provider. We will give you credit on the solution with a shoutout in our release note!

Thank you again for being part of the community of our Citrix Terraform Provider!

**Comment by j7lloyd** [comment]
Thank you for your swift response and valuable guidance. I confirm that, as suggested, I have submitted my proposed changes through a pull request, and I trust this will provide a clearer understanding of the potential improvements.

I am genuinely excited to contribute to this project, and I appreciate the opportunity to be part of the development process. I'm also grateful for the possibility of receiving credit for any code that you choose to use in a future release. I look forward to your insights and feedback in due course.

**Comment by zhuolun-citrix** [comment]
Thank you! We will keep you updated once we have the workflow for external contribution. 

We will review your opened PR and adopt the change in a future release.
