### ISSUE TITLE
Region not available as an argument in provider configuration

### ISSUE THREAD

**Issue by j7lloyd** [citrix/terraform-provider-citrix#57]
While it's not a major concern, the README suggests that the region can be specified when configuring the Cloud provider. However, there's no provision for this in the provider.go schema. Do you have any plans for when this feature will be available?

**Comment by AlanCitrix** [comment]
Thanks for pointing this out! It turns out that we did not need as many regions as we had expected, so `region` and `environment` were merged into a single field: https://registry.terraform.io/providers/citrix/citrix/latest/docs#environment

If you are using our US, EU, or AP-S cloud regions than your environment is `Production`. Japan customers can use `ProductionJP` and gov customers `ProductionGov`. Japan and gov get separate environments because they are configured as sovereign clouds.

I will take this issue to update the README to match our docs.
